"""update execution.updated_at onupdate

Revision ID: 7c44edfa2215
Revises: ec8748f70e4d
Create Date: 2025-09-24 17:01:58.069541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c44edfa2215'
down_revision: Union[str, Sequence[str], None] = 'ec8748f70e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'connection', ['id'])
    op.add_column('credential', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'credential', ['id'])
    op.drop_constraint(op.f('credential_userId_fkey'), 'credential', type_='foreignkey')
    op.create_foreign_key(None, 'credential', 'user', ['user_id'], ['id'])
    op.drop_column('credential', 'userId')
    op.create_unique_constraint(None, 'node', ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=254),
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'workflow', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_constraint(None, 'node', type_='unique')
    op.add_column('credential', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'credential', type_='foreignkey')
    op.create_foreign_key(op.f('credential_userId_fkey'), 'credential', 'user', ['userId'], ['id'])
    op.drop_constraint(None, 'credential', type_='unique')
    op.drop_column('credential', 'user_id')
    op.drop_constraint(None, 'connection', type_='unique')
    # ### end Alembic commands ###
